---
- name: Define phpfpm_pool_conf_path.
  set_fact:
    phpfpm_pool_conf_path: "{{ __phpfpm_pool_conf_path }}"
  when: phpfpm_pool_conf_path is not defined

- name: Define phpfpm_pool_user.
  set_fact:
    phpfpm_pool_user: "{{ __phpfpm_pool_user }}"
  when: phpfpm_pool_user is not defined

- name: Define phpfpm_pool_group.
  set_fact:
    phpfpm_pool_group: "{{ __phpfpm_pool_group }}"
  when: phpfpm_pool_group is not defined

- name: Stat phpfpm_pool_conf_path
  stat:
    path: "{{ phpfpm_pool_conf_path | dirname }}"
  register: phpfpm_pool_conf_path_dir_stat

- name: Ensure the default pool directory exists.
  file:
    path: "{{ phpfpm_pool_conf_path | dirname }}"
    state: directory
    owner: "{{ phpfpm_pool_user | default('root', true) }}"
    group: "{{ phpfpm_pool_group | default('root', true) }}"
    mode: 0755
    force: true
  when: phpfpm_pool_conf_path_dir_stat.stat.islnk is not defined

- name: Create fpm pools.
  template:
    src: "{{ item.pool_template | default('fpm-pool.conf.j2', true) }}"
    dest: "{{ phpfpm_pool_conf_path | dirname }}/{{ item.pool_name }}.conf"
    owner: "{{ phpfpm_pool_user | default('root', true) }}"
    group: "{{ phpfpm_pool_user | default('root', true) }}"
    mode: 0644
    force: true
  loop: "{{ phpfpm_pools | default([], true) }}"
